spring.application.name=project1

# Disable JPA/Database auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

# File storage configuration
app.storage.data-dir=data

# Static resources
spring.web.resources.static-locations=classpath:/static/
server.port=8085

# Allow circular references
spring.main.allow-circular-references=true